### ISSUE TITLE
Can not clear/ override the input value in v 1.0.3

### ISSUE THREAD

**Issue by olgaplaga** [axisj/react-multi-email#104]
There is currently no way to clear the input value before the email is transformed into the tile. 

The value is set while someone writes inside an input before the email address is finished and converted to the tile.  
At this moment, when I want to create for e.g an action button, that clears input from unfinished emails like this:

```
const input: HTMLInputElement | null = document.querySelector('.react-multi-email input')

input.value = '' // this will not work
```

This will not work, because the package overrides this process with the value. Please provide an option to clear the input from value.

**Comment by ojaspatharkar-qure** [comment]
same here. need provision to clear the input.

**Comment by LoveWithCoding** [comment]
@ojaspatharkar-qure , @olgaplaga Ddi you find the solution?

**Comment by ojaspatharkar-qure** [comment]
> @ojaspatharkar-qure , @olgaplaga Ddi you find the solution?

have you tried using `onChangeInput` props?

**Comment by Yandamuri** [comment]
> > @ojaspatharkar-qure , @olgaplaga Ddi you find the solution?
> 
> have you tried using `onChangeInput` props?

`onChangeInput` gives what ever we type(letter by letter). Can we remove input by using this prop?

**Comment by hovelopin** [comment]
@LoveWithCoding hello, 

Can you confirm if I understand this correctly?

Is this the issue where it doesn't work when I create a button externally and try to control the input value?

**Comment by Yandamuri** [comment]
> @LoveWithCoding hello,
> 
> Can you confirm if I understand this correctly?
> 
> Is this the issue where it doesn't work when I create a button externally and try to control the input value?



> @LoveWithCoding hello,
> 
> Can you confirm if I understand this correctly?
> 
> Is this the issue where it doesn't work when I create a button externally and try to control the input value?

let say if i type correct email and press tab then it will be shown as chip(with some background color). but some times user might leave the filed with half typed value which is any way not a valid email. In such a cases i want to remove the half typed value on OnBlur event. I do not want fields contain unfinished emails.

Is there a way to achieve this?

**Comment by thomasJang** [comment]
@hovelopin 

I just made a PR. PLZ review my code.
I thought a new PROP was needed to control INPUT values in the component. It can be used as in the following example.
```js
const [input, setInput] = useState<string>('');

return (
        <ReactMultiEmail
          inputValue={input}
          onChangeInput={value => {
            console.log(value);
            setInput(value);
          }}
        />
);
```

**Comment by Yandamuri** [comment]
> @hovelopin
> 
> I just made a PR. PLZ review my code. I thought a new PROP was needed to control INPUT values in the component. It can be used as in the following example.
> 
> ```js
> const [input, setInput] = useState<string>('');
> 
> return (
>         <ReactMultiEmail
>           inputValue={input}
>           onChangeInput={value => {
>             console.log(value);
>             setInput(value);
>           }}
>           onBlur={() => {
>             setInput('');
>           }}
>         />
> );
> ```

Exactly. this what I am looking for.

**Comment by thomasJang** [comment]
Now, you can use 1.0.24 

t can be used as in the following example.
```js
const [input, setInput] = useState<string>('');

return (
        <ReactMultiEmail
          inputValue={input}
          onChangeInput={value => {
            console.log(value);
            setInput(value);
          }}
          onBlur={() => {
            setInput('');
          }}
        />
);
```

**Comment by Yandamuri** [comment]
@thomasJang Thank you for this quick response. This solved the problem discussed here, but got new issue.

https://github.com/user-attachments/assets/1a710d08-adc0-46cb-aeb8-8f7d953a1d3c

when email is validated(When tapped on tab bar), email field renders redundant emails because of new prop `inputValue`. Is it possible to prevent rendering the `inputValue` once email is validated.

**Comment by thomasJang** [comment]
@Yandamuri 
Could you share your code?

**Comment by Yandamuri** [comment]
@thomasJang 

```
const MultiEmail = () => {
    const [tempInput, setTempInput] = useState('');
    const [emails, setEmails] = useState([]);

    return (
        <ReactMultiEmail
            placeholder="Type here"
            emails={emails}
            inputValue={tempInput}
            onChange={(emails) => setEmails(emails)}
            onChangeInput={(value) => setTempInput(value)}
            onBlur={() => setTempInput('')}
            getLabel={(email, index, removeEmail) => {
                return (
                    <div data-tag key={index}>
                        {email}
                        <span data-tag-handle onClick={() => removeEmail(index)}>×</span>
                    </div>
                );
            }}
        />
    );
}
```

**Comment by thomasJang** [comment]
@Yandamuri 
https://codesandbox.io/p/sandbox/react-multi-email-test-f79zn2

I don't think there's a problem when I check it on the link. Check it out.

**Comment by Yandamuri** [comment]
@thomasJang 
Still issue persists in the link you provided. I am not sure if understood the problem from my previous comment. Problem is redundant emails and it still exists.

[

https://github.com/user-attachments/assets/35d1467c-882c-4341-9a60-d076a634a891

](url)

OR Please correct me if i am missing something.

**Comment by thomasJang** [comment]
Are you using Windows? 
And did you enter the tab key after entering the email?

**Comment by hovelopin** [comment]
@Yandamuri can you press space?

**Comment by thomasJang** [comment]
@Yandamuri 
I've fixed the code. I'll let you know when it's distributed.
https://github.com/axisj/react-multi-email/pull/178

**Comment by Yandamuri** [comment]
> Are you using Windows? And did you enter the tab key after entering the email?

I am using MacBook and of course I pressed space bar(not the `tab` key).

**Comment by thomasJang** [comment]
Now, you can use 1.0.25 @Yandamuri

**Comment by Yandamuri** [comment]
@thomasJang Yes, It's working as expected. Thank you so much for your effort and prompt response.

It would be great if the `README.md` and version `change logs` are updated regarding these new changes. Please be notified that package version is still showing as `1.0.17` only
